### Ejercicios Clase 4: Introducción a Pandas


Para estos ejercicios vamos a seguir utilizando el recorte de un dataset sobre el establecimientos educativos en la Provincia de Buenos Aires extraído del sitio web de [Datos Abiertos de la Provincia de Buenos Aires](https://catalogo.datos.gba.gob.ar/dataset/establecimientos-educativos/archivo/3951210e-7e0e-4fed-bbf1-0183e704c9ae) actualizado a fines del año 2022.
En la clase vamos a usar un Dataset modificacado por lo que para ejectutar la Notebook correctamente se debe utilizar el archivo de la clase.

In [1]:
import pandas as pd

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

In [2]:
data = pd.read_csv("establecimientos_educativos.csv")

1. Ver 3 registros aleatorios del dataset

In [3]:
aleatorios = data.sample(3)
print(aleatorios)

       row_number  idserv       clave  cueanexo  \
16106       16107   19245  0008MS0028  61733600
6326         6327    6624  0078AA0001  61492100
9383         9384    9875  0119PP0002  61014800

                                                  nombre            modalidad  \
16106               ESCUELA DE EDUCACIÓN SECUNDARIA Nº28      Educación Común
6326              ESCUELA DE ARTE Nº1 "ALCIDES BIAGETTI"  Modalidad Artística
9383   ESCUELA DE EDUCACIÓN PRIMARIA Nº2 "JUAN JOSÉ P...      Educación Común

                     nivel     periodo            calle  nro  ...  \
16106     Nivel Secundario  Final 2022          DORREGO  545  ...
6326   Ciclo de Iniciación  Final 2022     BUENOS AIRES  456  ...
9383        Nivel Primario  Final 2022  54 E/ 158 Y 159  S/N  ...

                   tipo_organizacion matricula varones mujeres  \
16106             ESCUELA SECUNDARIA       260     106     154
6326                 ESCUELA DE ARTE       100      30      70
9383   ESCUELA DE EDUCACIÓN PRIMARIA       622     326     296

                        turnos       area sede_axo_ext esc_sede    latitud  \
16106             MAÑANA,TARDE   INTERIOR         SEDE      NaN -38.719004
6326   MAÑANA,TARDE,VESPERTINO   INTERIOR         SEDE      NaN -40.793982
9383              MAÑANA,TARDE  CONURBANO         SEDE      NaN -34.788785

        longitud
16106 -62.255810
6326  -62.987877
9383  -58.162419

[3 rows x 29 columns]

2. Ver la cantidad de registros y columnas del dataset

In [3]:
registros = data.shape
print("Filas:", registros[0], "\tColumnas:", registros[1])

Filas: 21623 	Columnas: 29

3. Seleccionar únicamente la columna "tipo_organización"

In [13]:
columna = data["tipo_organizacion"] 
# columna = data.tipo_organizacion
print(columna)

0                          ESCUELA DE DANZAS CLÁSICAS
1                          ESCUELA DE DANZAS CLÁSICAS
2                          ESCUELA DE DANZAS CLÁSICAS
3                      ESCUELA DE EDUCACIÓN ARTÍSTICA
4                      ESCUELA DE EDUCACIÓN ARTÍSTICA
                             ...
21618                 CENTRO DE FORMACIÓN PROFESIONAL
21619                             POLIVALENTE DE ARTE
21620    JARDÍN DE INFANTES RURAL DE MATRÍCULA MÍNIMA
21621    JARDÍN DE INFANTES RURAL DE MATRÍCULA MÍNIMA
21622    JARDÍN DE INFANTES RURAL DE MATRÍCULA MÍNIMA
Name: tipo_organizacion, Length: 21623, dtype: object

4. ¿Cuáles son los posibles niveles de los establecimientos? ¿Cuántos hay de cada uno? Utilizar* unique()* y *value_counts()*

In [25]:
niveles =  data.nivel.unique()
cantidad = data.nivel.value_counts()

print("Posibles niveles educativos:\n", niveles)
print("\nDe cada nivel tenemos:\n", cantidad)

Posibles niveles educativos:
 ['Ciclo de Iniciación' 'Nivel Superior (**)' 'Ciclo Medio'
 'Cursos y Talleres' 'Nivel Primario' 'Nivel Inicial' 'Formación Integral'
 'Formación Profesional' 'Residencia Laboral,Pasantias, Artística'
 'Educación Física (C.E.F.)' 'Nivel Secundario' 'Nivel Medio'
 'Plan Fines (Trayectos y Deudores)'
 'Psicología Comunitaria y Pedagogía (C.E.C)']

De cada nivel tenemos:
 nivel
Nivel Primario                                7485
Nivel Inicial                                 6111
Nivel Secundario                              4721
Formación Profesional                          662
Nivel Superior (**)                            643
Nivel Medio                                    575
Formación Integral                             567
Educación Física (C.E.F.)                      196
Psicología Comunitaria y Pedagogía (C.E.C)     188
Plan Fines (Trayectos y Deudores)              171
Cursos y Talleres                               95
Residencia Laboral,Pasantias, Artística         78
Ciclo de Iniciación                             72
Ciclo Medio                                     59
Name: count, dtype: int64

5. Eliminar la columna "row_number"

In [30]:
print("Todas las columnas:\n", data.columns)

data_nuevo = data.drop(columns="row_number")
print("\nLuego de borrar:\n", data_nuevo.columns)

Todas las columnas:
 Index(['row_number', 'idserv', 'clave', 'cueanexo', 'nombre', 'modalidad',
       'nivel', 'periodo', 'calle', 'nro', 'localidad', 'distrito',
       'region_educativa', 'depend_func', 'desfavorabilidad', 'subvencion',
       'ubicacion', 'sector', 'dependencia', 'tipo_organizacion', 'matricula',
       'varones', 'mujeres', 'turnos', 'area', 'sede_axo_ext', 'esc_sede',
       'latitud', 'longitud'],
      dtype='object')

Luego de borrar:
 Index(['idserv', 'clave', 'cueanexo', 'nombre', 'modalidad', 'nivel',
       'periodo', 'calle', 'nro', 'localidad', 'distrito', 'region_educativa',
       'depend_func', 'desfavorabilidad', 'subvencion', 'ubicacion', 'sector',
       'dependencia', 'tipo_organizacion', 'matricula', 'varones', 'mujeres',
       'turnos', 'area', 'sede_axo_ext', 'esc_sede', 'latitud', 'longitud'],
      dtype='object')

6. ¿Cuál es la matricula de mujeres total de todos los establecimientos?

In [35]:
mujeres = data.mujeres.sum()
print("Total de mujeres:", mujeres)

Total de mujeres: 2590168